# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: same_level.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10same_level.proto\"<\n\x04\x43ity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08zip_code\x18\x02 \x01(\x05\x12\x14\n\x0c\x63ountry_name\x18\x03 \x01(\t\"0\n\x06Street\x12\x13\n\x0bstreet_name\x18\x01 \x01(\t\x12\x11\n\tcity_name\x18\x02 \x01(\t\"J\n\x08\x42uilding\x12\x15\n\rbuilding_name\x18\x01 \x01(\t\x12\x17\n\x0f\x62uilding_number\x18\x02 \x01(\r\x12\x0e\n\x06street\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'same_level_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CITY._serialized_start=20
  _CITY._serialized_end=80
  _STREET._serialized_start=82
  _STREET._serialized_end=130
  _BUILDING._serialized_start=132
  _BUILDING._serialized_end=206
# @@protoc_insertion_point(module_scope)
